Mindwerks/worldengine

- worldengine/cli/main.py
For convenience purposes I suggest that we can create the output directory if it does not exist.
> Lets create an output directory if it does not exist

- requirements_base.txt
- setup.py
Open a Pull Request so that Travis and AppVeyor verify if everything is fine with Numpy 1.9.2
The reason to move to Numpy 1.9.2 is that previous versions has no wheel packages for Windows as reported by @SourceRyan (see #69)
> move to numpy 1.9.2

- worldengine/cli/main.py
I am not sure what the wanted behaviour is, but this looked like it might be unintentional. Since the seed wasn't used to seed the random generator, successive calls to random() of any kind (which occur at several points in the code) gave actual random results, even when a seed was given.
This patch makes the seed be the actual seed of the random generator. This got rid of some of the problems I was having when trying to modify the ocean_level variable so that it can actually modify the ocean level. That is not done yet, however.
It also got rid of the remaining lack of deterministicness I saw when regenerating a world with the same seed (there were some slight changes in colors...hopefully weren't my eyes).
If this proves useful, the seed-variable could probably be removed as a parameter …
> The random generator now properly uses the seed to produce deterministic results.

- worldengine/cli/main.py
Since the actual filenames of grayscale- and rivers-map follow the same pattern as all the other maps, I found it annoying that the generated maps aren't just all placed in the same directory. Kind of makes it difficult to (auto-)generate several maps at once (I wrote a script to generate half a dozen decently sized maps while I'm away and the files being spread around doesn't feel right).
This might seem a bit dirty, there may be other filenames I overlooked. But somebody else shall look at it and decide if the commit is useful or needs some polish.
EDIT: I won the coveralls-lottery.^^
> Changed paths for grayscale- and rivers-map.

- tests/serialization_test.py
- worldengine/simulations/irrigation.py
- worldengine/world.py
I played around with a profiler, picked out one of the slowest functions and took a look at what could be improved - I found a couple of smaller things, but nothing major. I then proceeded to see what numpy could do - but it actually doesn't do much. Speed improvements are within the margin of error, memory improvements weren't measurable due to me not knowing how to properly use memory_profiler.
The generated maps are 100% the same as before, result of the tests hasn't changed either.
Here some more information, not very useful and quite boring: http://pastebin.com/8p1vwaV1
> A bit of NumPy

- requirements.txt
- setup.py
Let's take advantage of the speed improvements we got in the new version of plate-tectonics/pyplatec
> Adopt pyplatec 1.4.0

- tests/blessed_images/generated_blessed_images.py
- tests/draw_test.py
- worldengine/cli/main.py
- worldengine/draw.py
This raises the minimum altitude of the land to sea level and then normalizes the elevation values to the range of 1 to 12 for the colored elevation map. This prevents the need of repeating color bands to represent higher ranges. As elevation has no inherent value the normalization causes no real distortions. The raising of the minimum land value means there is no land with an altitude above sea level (something which can occur in the real world) but it makes the elevation map easier to import into other programs such as Fractal Terrains and such a solution is already used in the grayscale height maps.
This modification will affect the output of the colored elevation map to an extent where any blessed images of elevation maps will need to be recalculated.
> Modification to the routines for drawing colored elevation maps.

- tests/basic_map_operations_test.py
- worldengine/basic_map_operations.py
- worldengine/cli/main.py
- worldengine/drawing_functions.py
- worldengine/generation.py
- worldengine/plates.py
- worldengine/simulations/erosion.py
- worldengine/simulations/hydrology.py
- worldengine/simulations/irrigation.py
- worldengine/simulations/permeability.py
- worldengine/simulations/precipitation.py
- worldengine/simulations/temperature.py
- worldengine/world.py
Here the replacement of all uses of the random-module with respective numpy-methods.
Since this is kind of a break with save-compatibility and...everything, I guess, I also took the freedom to include some small changes so they aren't necessary in the future - I will add comments to the code to point them out and explain them.
Notes:
1. This is based on https://github.com/Mindwerks/worldengine/pull/138 .
2. This does not pass the ancient-map tests (since that one uses RNG to determine its outcome)
> random -> numpy.random

- tests/cli_test.py
- tests/generation_test.py
- tests/serialization_test.py
- worldengine/cli/main.py
- worldengine/plates.py
- worldengine/simulations/humidity.py
- worldengine/simulations/temperature.py
- worldengine/world.py
Added command line options for Temperature and Humidity ranges. While this does not fully allow the creation of non-terrestrial planets (we need to be able to alter how much water there is) it brings us much further along.
$ python worldengine -b -s 1 --temps 1/1/1/1/0.594/0.439  --humidity .507/.236/.073/.014/.002/.0/.0
Worldengine - a world generator (v. 0.18.0)
-----------------------
operation         : world generation
seed                 : 1
name                 : seed_1
width                : 512
height               : 512
number of plates     : 10
world format         : protobuf
black and white maps : False
step                 : full
greyscale heightmap  : False
rivers map           : False
fade borders         : True
temperature ranges   : [1.0, 1.0, 1.0, 1.0, 0.594, 0.439] …
> Temperature and Humidity parameters can be altered from the command line.

- tests/cli_test.py
- tests/draw_test.py
- worldengine/cli/main.py
- worldengine/draw.py
- worldengine/generation.py
- worldengine/simulations/humidity.py
- worldengine/simulations/precipitation.py
- worldengine/simulations/temperature.py
Added a new command line option; --scatter.
This will draw a scatter plot of all land elements with the normalized temperature along the x axis and the normalized humidity along the y axis. This will be useful for fine tuning humidity and temperature routines.
> Added new scatter plot

- worldengine/simulations/temperature.py
I added a bit of code to give temperature maps a little more character. Something that would be very good to know is: Does the temperature map have an influence on the placement of biomes? I thought I saw something like that but I am not sure anymore. If it did, then this little feature might have very interesting results. :)
Here are some examples of small maps - discussion is welcome, of course:
This branch is based off of https://github.com/Mindwerks/worldengine/pull/138 because it is getting a bit difficult to code around all the small changes I made in the numpy-branches without making git hiccup.
A little more information: In theory the obliquity of the planet can go up to 90 degrees but since I used a pretty tight Gaussian distribution that is very unlikely to happen. Values might …
> Temperature variation based on orbital parameters

- worldengine/draw.py
- worldengine/drawing_functions.py
- worldengine/plates.py
- worldengine/simulations/basic.py
- worldengine/world.py
Another portion of the code in https://github.com/Mindwerks/worldengine/pull/141 . Some very small changes and quite a lot of changes in the draw- and drawing_functions-modules.
This again is based off of https://github.com/Mindwerks/worldengine/pull/146 .
Tests will fail for now due to some differences in rounding for the grayscale-map.
> numpy-replacements for image-drawing

- README.md
This PR fixes the link to the GUI project on the README file.
> Fix link to worldengine-gui project

- MANIFEST.in
- worldengine/cli/main.py
- worldengine/simulations/humidity.py
- worldengine/simulations/precipitation.py
Problem described here: https://github.com/Mindwerks/worldengine/issues/158
I used @psi29a 's suggestion regarding the addition to ```MANIFEST.in```.
> Fixes to make pyflakes- and manifest-tests run again.

- worldengine/cli/main.py
- worldengine/imex/__init__.py
This originally went into https://github.com/Mindwerks/worldengine/pull/141 (which happened due to me working on too many things at once). I now separated it to make things easier for everybody.
I decided to make some rather big changes to the way GDAL export is handled: I think the commandline interface is now a little bit easier to use, and the changes to ```imex/__init__.py``` actually allow the user to make use of every format GDAL can handle while hopefully not making things more complicated than they were before.
I based this off of https://github.com/Mindwerks/worldengine/pull/146 even though it wasn't strictly necessary. I figured that discussing the changes happening here would take longer than merging the other PR anyway.
Here the link to the only commit that is relevant: …
> Rework of GDAL-export

- worldengine/cli/main.py
- worldengine/draw.py
- worldengine/generation.py
Here is a pull request with the proper issues sorted out.
This branch adds functionality for creating a "Satellite map" of the generated world. This is currently an option, default false, toggled on with the --sat command when running.
Additional work may need to be done in selecting more appropriate biome colors and tuning the algorithm to display elevation / shading, to get a more realistic result.
Some sample outputs are attached here:
> Satellite map (non-messed-up version)

- requirements.txt
- setup.py
- tests/blessed_images/generated_blessed_images.py
- tests/draw_test.py
- tests/drawing_functions_test.py
- tox.ini
- worldengine/draw.py
- worldengine/drawing_functions.py
- worldengine/generation.py
- worldengine/image_io.py
- worldengine/simulations/erosion.py
This is the setup I am using to generate 16 Bit grayscale heightmaps, extracted from the (now dead) #141 . There is a big chunk of code here that is basically a drop-in replacement of the ImageWriter-class used so far (I gave it its own file). Technically that class could be used to write all images (which would remove the Pillow-dependency) but I didn't want to go in too deep again. Maybe later.
The tests won't be passed until I also update the grayscale heightmap in worldengine-data. That can happen once the code here is acceptable, I think.
EDIT: I had to base this off of #161 , currently only the last two commits here are actually new.
PS: I will try hard to keep this my last PR until all others are handled. ;)
> 16 Bit grayscale heightmaps

- tests/biome_test.py
- tests/blessed_images/generated_blessed_images.py
- tests/data/data_generator.py
- tests/drawing_functions_test.py
- tests/generation_test.py
- tests/serialization_test.py
- worldengine/cli/main.py
- worldengine/simulations/erosion.py
- worldengine/world.py
Since I wanted to [add a new variable to the World](https://github.com/Mindwerks/worldengine/pull/189) I noticed that I couldn't regenerate the pickle test-worlds after https://github.com/Mindwerks/worldengine/pull/187 had been merged (I did it via a bash-script before, but WorldEngine didn't take a parameter to output a pickle-world anymore).
After a bit of thinking I noticed that "load-only support" for pickle is worthless once new variables are added to the world since compatibility will most likely be lost anyway; @psi29a [seemed to agree](https://github.com/Mindwerks/worldengine/pull/187) that pickle-support could probably be purged completely.
So what this does might seem a lot:
* completely remove pickle-support
* update ```data_generator.py``` so it actually outputs all necessary …
> Removed (almost) every last trace of support for pickle

- worldengine/cli/main.py
I seemingly forgot to make clear that the GDAL-parameters need some kind of string to be passed.
> Repaired commandline-parameters for GDAL-export

- CHANGELOG.md
- README.md
I only updated what I knew of; might have overlooked some things.
(I also reordered the bullet points in the changelog a bit - changes first, then additions, then removals.)
> Updates to README and CHANGELOG

- README.md
Some of the first sentences in the README seemed a little rough to me.
I think this should be compatible with https://github.com/Mindwerks/worldengine/pull/198.
> Rephrasing some sentences in the README

- worldengine/imex/__init__.py
When running export in Windows, errors out: "WindowsError: [Error 32] The process cannot access the file because it is in use by another process: path_to_temp_file"
Flushing (new line 132) and adding a call to close with the file handle (new line 134) resolves the error. Just flushing, or just closing, does not.
Thanks!
> Update __init__.py - resolve Windows error 32

- worldengine/cli/main.py
- worldengine/generation.py
- worldengine/hdf5_serialization.py
- worldengine/model/world.py
- worldengine/plates.py
- worldengine/simulations/biome.py
- worldengine/simulations/erosion.py
- worldengine/simulations/humidity.py
- worldengine/simulations/hydrology.py
- worldengine/simulations/icecap.py
- worldengine/simulations/irrigation.py
- worldengine/simulations/permeability.py
- worldengine/simulations/precipitation.py
- worldengine/simulations/temperature.py
Trying to be helpful and resolve #209
I did not run this project, so the code is need to be carevully reviewed and tested
> Convert setters to properties

- worldengine/draw.py
- worldengine/imex/__init__.py
This pull request fixes #235 and makes the following type of command line interactions work again:
```
python worldengine --ice -n foo
python worldengine export foo.world
```
> Fix AttributeError: 'World' object has no attribute

- worldengine/generation.py
Here's another one I prepared yesterday.
This uses the fact that only very few coodinates are actually `dist` away from land. It then iterates over these coordinates and looks if the distance of their neighbours happens to be unknown. Only then an update is made. This is actually the more logical thing to do because it checks for `dist` directly at the beginning of the loop iterating over `dist` and it checks `next_land[ny,nx]` in the inner loop and makes a change to the same coordinate. 
The original implementation had this backwards. It checked for unknown distances in the outer loop and for the known distance in the inner loop which makes for a lot more checks because of how the numbers work out.
I think that change in ordering is where the main speedup comes from. Doing the more …
> transpose next_land_dynamic for greater speed and clarity

- worldengine/model/world.py
- worldengine/simulations/erosion.py
This is the last thing I had prepared. 
I discovered that `numpy.tolist` does the main thing of what `_to_protobuf_matrix` is trying to do sans transformation. We can also use numpy to vectorise the transformation which looks a bit cleaner. 
I also picked the extremely low hanging fruit of making the iteration order in `river_sources` cache friendly.
Again this is not that much faster ~10s for the 1024*512 map.
Here is how the final timing of 2m12s is mostly spent:
- ~16% `platec.step` (as discussed in #246)
- ~6% `irrigation.calculate` (somebody already took numpy to that problem, so there is little to be gained, I assume)
- ~6% `protobuf.internal.encoder.EncodeRepeatedField` (mostly type checks, AFAICT)
- ~5% `PNGWriter.set_pixel` (maybe a faster numpy->image format will fall out of my …
> Final speedup PR

- worldengine/common.py
- worldengine/drawing_functions.py
- worldengine/model/world.py
In absolute timing this takes about 10s off the clock for a 1024*512 map. Relative timings are dominated by anti-aliasing, but I thought I'd do this while waiting for #251 to be resolved. 
Code is also a bit cleaner, once again.
Not much more to be said about this one.
> improved mountain mask

- README.md
- tests/drawing_functions_test.py
- worldengine/drawing_functions.py
- worldengine/model/world.py
Hi again,
this more or less completely refactors `draw_ancient_map`. It is part of my effort to get rid of the slow `*_tiles_around_*` functions. 
Almost nothing is where it used to be, again to the point where the diff is almost useless, so let me highlight some changes:
* `find_land_borders` and `find_outer_borders` both use the scaled ocean. So it would be nice if they were in the same scope as to share that. They also both can be expressed in very few lines of code. So I moved them into `draw_ancientmap` proper.
* biome drawing code looked a bit differently for each biome but in the end only three different concepts were used. The new `_draw_biome` caters almost all our biome drawing needs. I'll try to get rid of the glacier special case next, btw.
* this results in verbose mode …
> Refactor ancient map

- README.md
Corrected heading tag for the manual on the Readme. Link is already there, so you could close #226.
> Corrected Heading for the Manual on the Readme
