Mindwerks/worldengine

requirements_base.txt
setup.py

Adopting noise 1.2.2

---

README.md
worldengine/cli/main.py

The info operation print on screen basic information about a saved world file.
In the future we could add more information (like the average elevation of the number of cells for each biome type)

Add info operation

---

README.md
worldengine/cli/main.py
worldengine/draw.py
worldengine/world.py

We add an option to generate black and white maps and we adapt temperature and precipitations drawing routines to consider that option.
See #74 and #75

Black and white temperature and precipitations map

---

.travis.yml
appveyor.yml
appveyor/install.ps1
requirements_base.txt
requirements_extras.txt

try to get gdal into windows via appveyor

---

CHANGELOG.md
MANIFEST.in
tests/cli_test.py
worldengine/cli/main.py
worldengine/draw.py

This should take care of:
https://github.com/Mindwerks/worldengine/issues/113

handle bad filenames

---

requirements-gdal.txt
setup.py

Two tiny things that have made my eyes sore for a while. (Unimportant under almost all circumstances, yes.^^)
EDIT: And I think that we don't have to restrict ourselves to a specific version of numpy. I wouldn't expect major changes there. (Does that have to be changed in requirements.txt, too?)

Two very small changes to the setup-files.

---

tests/blessed_images/generated_blessed_images.py
tests/data/data_generator.py
tests/drawing_functions_test.py
tests/generation_test.py

If this is ok, I will follow up with an update to my PR at worldengine-data.
https://github.com/Mindwerks/worldengine-data/pull/1

Tests: Differentiate between Python 2 and Python 3 saves

---

docs/Biomes.html

I'm going to write up a document to outline the various biomes. Mostly I'll probably be cutting and pasting from various other sources.
Right now the document just has a chart that shows the colors and color codes for the various biomes and groups them according to Leeman's aggregation of the Holdridge life zones. I had a document at one point that spelled out what the various zones were in better detail but I can't find it at the moment. As I do I will update the doc.

Added initial biomes document. 

---

README.md
worldengine/cli/main.py
worldengine/plates.py

issue56: add option to control fading borders

---

tests/blessed_images/generated_blessed_images.py
worldengine/generation.py

This is a simple approach to solve the issue of noisy ocean floors (issue #60)

Armonize ocean floor

---

tests/biome_test.py

Requires biome_test.world which is pull request #4 on worldengine-data

Added a test to provide better coverage for simulations/biome.py

---

worldengine/cli/main.py
worldengine/drawing_functions.py
worldengine/simulations/erosion.py

We already calculated rivermap and lakemap but then we used an ad-hoc routine to draw rivers, with questionable results.
This patch is built on top of #167 
See images in #119

Rivers worldsynth

---

tests/cli_test.py
tests/generation_test.py
tests/serialization_test.py
worldengine/cli/main.py
worldengine/draw.py
worldengine/plates.py
worldengine/simulations/precipitation.py
worldengine/world.py

Also minor code cleanup.
Modified scatter plot to show gamma correction curve.

Added command line options for temperature/precipitation gamma correction curve.

---

worldengine/cli/main.py

Just a small change after @psi29a found out how to pull the correct values from numpy.

Changed seed-range for platec-seeds to use numpy constant.

---

worldengine/generation.py

Since the change was removed from #181 , I decided to put it in so it isn't forgotten about.

Changed maximum seed-value in generation.py

---

worldengine/cli/main.py

pickle: protobuf: make protobuf the default format instead of pickle

---

tests/blessed_images/generated_blessed_images.py
tests/data/data_generator.py
tests/draw_test.py
worldengine/draw.py

I tried to add a test for the satellite-view (and added a couple lines of code to properly test the scatter-plot).
I think I might have chosen a bad time for this since @pangal might want to continue work on this himself...but I thought this might be a quick change. It isn't, sadly, so far I haven't gotten the code to pass the satellite-test. I don't really know why, but maybe somebody sees the flaw.
EDIT: Here the data-PR https://github.com/Mindwerks/worldengine-data/pull/12, even though this should **not be merged right now** due the failed final test.
EDIT2: If @pangal (or somebody else) wants to continue work on this, I could probably rebase this PR, so please don't hesitate. :)
**EDIT3:** This is now based on #163.

New Tests; Several Bug-Fixes

---

docs/Biomes.html
manual/biomes.rst
manual/index.rst

Created manual page to hopefully explain how --temps, --humids, -go, and -gv work.
I tried to be clear and concise while supplying full details, tasks which are often at odds with one another. Please let me know if things are unclear, redundant, overly verbose, etc.

Biomes manual

---

README.md

@ftomassetti  Please review.
#226 is resolved

chore(manual): link to manual in readme

---

worldengine/cli/main.py
worldengine/imex/__init__.py

Makes our GDAL support more robust!

Additional gdal

---

tests/common_test.py
worldengine/common.py

Hello again,
anti_alias sported this comment:
> #TODO: There is probably a bit of numpy-optimization that can be done here.
That's exactly what I did. It is now much faster.
Cheers
Alex

reimplemented _anti_alias_step to use numpy

---

CHANGELOG.md
worldengine/common.py
worldengine/drawing_functions.py

This fails the test as discussed in #250 
The blessed image would have to be changed. It is two full minutes (~66%) faster on a 1024*512 map on my machine though.

Ancient map anti alias

---

.gitignore
Dockerfile
MANIFEST.in
README.md
bin/run_in_docker.sh

Hi there, this allows users to run worldengine without worrying about dependencies, or worry about dirtying-up their local machine.

Enable easy install and run with Docker

---

setup.py
tests/basic_map_operations_test.py
tests/common_test.py
worldengine/cli/main.py
worldengine/image_io.py

Recent versions of numpy changed vstack inputs, also fixed some warnings
Following #261

Fixes numpy and warnings
